- name: print vars
  hosts: AS
  become: yes
  vars_files:
  - text.yaml
  tasks:
  
  - name: 
      ansible.builtin.debug:
        msg: "this is a course details {{ course }}, {{syllabus}}, {{topics}}"