- name: print vars
  hosts: AS
  become: yes
  vars:
    course: computing
    syllabus: general
    topics:
    - IAM
    - aws
    - cloud
    - server 
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "this is a course details {{ course }}, {{syllabus}}, {{topics}}"