- name: register user
  hosts: AS
  become: yes

  tasks:
  - name: check user
    andible.builtin.command: id expense
    register: user
  - name: print the user
    ansible.builtin.debug:
      msg: "{{user}}"
