- name: regarding data types
  hosts: AS
  become: yes
  #connection: local
  vars_prompt:
  - name: number
    prompt: enter the number
    private: false
  tasks:
  - name: tasklevel
    ansible.builtin.debug:
      msg: "print {{ number}} "
    when: number | integer > 10

