- name: regarding data types
  hosts: AS
  become: yes
  #connection: local
  vars: 
    course: cloud #string
    cloud: 01 #interger
    systems: servers
    topics: #list
     - linux
     - shell
     - ansible
     - aws
     - k8
    live: true #boolean
    tools: # map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
    tasks:
    - name: tasklevel
      ansible.builtin.debug:
            msg: "{{tools}}, {{material}}, {{topics}}"

